// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMy8ceFoayYT-9hKKBlSrE-I_hvjFZenk',
    appId: '1:114776433538:web:45f80d268120cb36e6a59b',
    messagingSenderId: '114776433538',
    projectId: 'projeto-todo-list',
    authDomain: 'projeto-todo-list.firebaseapp.com',
    databaseURL: 'https://projeto-todo-list-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-todo-list.firebasestorage.app',
    measurementId: 'G-P1H4XXVK69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7PM9CmAp0qW1_hfLzfB6MMRCE6go6Xjc',
    appId: '1:114776433538:android:a3328b73ac77b0c0e6a59b',
    messagingSenderId: '114776433538',
    projectId: 'projeto-todo-list',
    databaseURL: 'https://projeto-todo-list-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-todo-list.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWGjAJYdTQOeWtuMNi1VIwTW9x7LmLCZw',
    appId: '1:114776433538:ios:cfd37a754363443fe6a59b',
    messagingSenderId: '114776433538',
    projectId: 'projeto-todo-list',
    databaseURL: 'https://projeto-todo-list-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-todo-list.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWGjAJYdTQOeWtuMNi1VIwTW9x7LmLCZw',
    appId: '1:114776433538:ios:cfd37a754363443fe6a59b',
    messagingSenderId: '114776433538',
    projectId: 'projeto-todo-list',
    databaseURL: 'https://projeto-todo-list-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-todo-list.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMy8ceFoayYT-9hKKBlSrE-I_hvjFZenk',
    appId: '1:114776433538:web:4c8de37e88b4cdc7e6a59b',
    messagingSenderId: '114776433538',
    projectId: 'projeto-todo-list',
    authDomain: 'projeto-todo-list.firebaseapp.com',
    databaseURL: 'https://projeto-todo-list-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-todo-list.firebasestorage.app',
    measurementId: 'G-Z91KQZHQ6D',
  );
}
